#!/bin/bash

# usage: RunTest ["command"] ["stagelist"]  
RunTest()
{
    if [ -z "$1" ] || [ -z "$2" ];then
        return 0
    else
        CMD=$1
        Staged=$2
        echo "$Staged" | while read -r address;do 
            result=`$CMD "$address" 2>&1`  
            if [ $? != 0 ]; then
                case $CMD in
                    "php -l")
                        echo -e "Check for file \"$address\" failed, result is:\n$result"
                        ;;
                    "phpcs --standard=Xamin")
                        echo -e "Codesniffer check on \"$address\" failed, result is:\n$result"
                        ;;
                    "jshint")
                        echo -e "Check for file \"$address\" failed, result is:\n$result"
                        ;;
                    "pep8")
                        echo -e "you've syntax issue in \"$address\": \n$result"
                        ;;
                    "pep257")
                        echo -e "you've missed docstring standards in \"$address\":\n$result"
                        ;;
                esac
                return 1
            fi
        done
    fi
    return 0
}

FindInvalidKeys()
{
    if [ -z "$1" ] || [ -z "$2" ];then 
        return 0
    else
        Staged=$1
        InvalKeys=$2
        echo "$Staged" | while read -r address;do
            for key in $InvalKeys;do
                result=`grep -iHn $key "$address" 2>&1`
                if [ $? == 0 ]; then 
                    echo "Found invalid keyword : $address : $result"
                    return 1
                fi
            done
        done
    fi
    return 0
}

PHPInvalidKeys="xdebug_break var_dump print_r"
Staged=`git diff --staged --cached --name-status`
Staged=`echo "$Staged" | grep -v "^D" | sed -e 's/^.\t//g'`

StagedJS=`echo "$Staged" | grep "\.js$"`
StagedPHP=`echo "$Staged" | grep "\.php$"`
StagedPY=`echo "$Staged" | grep "\.py$"`

code=0

ret=$(RunTest "php -l" "$StagedPHP")
if [ ! -z "$ret" ]; then
  printf "$ret"
  exit 1
fi
ret=$(FindInvalidKeys "$StagedPHP" "$PHPInvalidKeys")
if [ ! -z "$ret" ]; then
  printf "$ret"
  exit 1
fi

ret=$(RunTest "phpcs --standard=Xamin" "$StagedPHP")
if [ ! -z "$ret" ]; then
  printf "$ret"
  exit 1
fi

ret=$(RunTest "pep8" "$StagedPY")
if [ ! -z "$ret" ]; then
  printf "$ret"
  exit 1
fi

ret=$(RunTest "pep257" "$StagedPY")
if [ ! -z "$ret" ]; then
  printf "$ret"
  exit 1
fi

ret=$(RunTest "jshint" "$StagedJS")
if [ ! -z "$ret" ]; then
  printf "$ret"
  exit 1
fi


exit 0

